---
title: "CBM Spades Manual"
subtitle: "`r paste('v.', Sys.getenv('SpadesCBM_MAN_VERSION'))`"
author: "Céline Boisvenue"
date: "26 June 2024"
output: pdf_document
editor_options: 
  chunk_output_type: console
---
```{r setup-CBM_core, include = FALSE}
```

# CBM_core

:::{.rmdimportant}
This documentation is work in progress. Potential discrepancies and omissions may exist for the time being. If you find any, please contact us [here]("https://github.com/PredictiveEcology/CBM_core/issues").
:::

## Overview

[CBM_core](https://github.com/PredictiveEcology/CBM_core.git) is the central module of [spadesCBM](https://github.com/PredictiveEcology/spadesCBM.git). This is where all the carbon transfers are calculated at every time step, where disturbances are applied, and stocks are tracked. It doesn't run on its own, it needs parameters from either [CBM_defaults](https://github.com/PredictiveEcology/CBM_defaults.git), [CBM_dataPrep_SK](https://github.com/PredictiveEcology/CBM_dataPrep_SK.git), and [CBM_vol2biomass](https://github.com/PredictiveEcology/CBM_vol2biomass.git) (as per the provided example for managed forests of Saskatchewan) or the equivalent information from the user. In *SpaDES-speak*, this module has five events (`Init`, `spinup`, `postspinup`, `annual`, `accumulateResults`). Only in two of these events do carbon transactions occur: `spinup` and `annual`. The other events are tools to enable these transactions. All events are scheduled only once except for the `annual` event, who schedules itself until the end of the simulation horizon. Only in this module are the Python functions from the [libcbm](https://github.com/cat-cfs/libcbm_py/tree/main) package called. The functions used in this module are the [libcbm cbm-exn](https://github.com/cat-cfs/libcbm_py/tree/main/libcbm/model/cbm_exn) exclusively, these were designed to accept external biomass increments. These are used in the `spinup` and in the `annual` events only.

## Background

In [CBM_core](https://github.com/PredictiveEcology/CBM_core.git), the approach described in our [Overview](link to the overview section) section applied. Parameters are easily accessible via normal R-functions, and the SpaDES toolkit enables a modular, repetable contiuous workflow. This brings the transparency and flexibility needed for scientist to modify, evaluate and test new inputs, new data, and new algorithms while permitting non-researcher users to use the system.


## Inputs

| Name              | Class      | Description                                                  | Source          |
|-----------------|-----------------|-----------------------|-----------------|
| growth_increments | Data table | growth increment matrix | CBM_vol2biomass |
| level3DT          | Data table | pixelGroup level table with all collapsed raster information | CBM_dataPrep_SK |
| spatialDT         | Data table | Pixel level table with all collapsed raster information      | CBM_dataPrep_SK |
| masterRaster      | SpatRaster | Raster of study area | User provided, for SK: [Google Drive](https://drive.google.com/file/d/1zUyFH8k6Ef4c_GiWMInKbwAl6m6gvLJW)                                                             |
| pooldef           | Character  | Vector of pools                                              | CBM_defaults    |
| spinupSQL         | Data table | Parameters for CBM_core spinup event                         | CBM_defaults    |
| speciesPixelGroup | Data table | Data table | Table connecting pixel groups to species IDs | CBM_dataPrep_SK |
| realAges | Numeric | Extracted ages for each pixel group | CBM_dataPrep_SK |
| mySpuDmids | Data table | Summary table of possible CBM-CFS3 disturbances within study area spatial units | CBM_dataPrep_SK |
| disturbanceRasters | Character | Disturbance rasters for the study area for the duration of simulation | User provided, for SK: [Google Drive](https://drive.google.com/file/d/12YnuQYytjcBej0_kdodLchPg7z9LygCt) |
| disturbanceMatrix | Data table | Default disturbance data                                     | CBM_defaults    |
| historicDMtype | Numeric | Historical disturbance type for each pixel group | CBM_dataPrep_SK |
| lastPassDMtype | Numeric | Last pass disturebance type for each pizel group | CBM_dataPrep_SK |

## Module functioning

### Events
There are 5 events in CBM_core. Each are run once, except for the `annual` event, which is run for each simulation year. 

#### `init`
In this short event, the Python virtual environment is set up. If a suitable version of python is not available, it will be installed using the `reticulate` package. 
If you are using a Windows computer with Git installed, the [pyenv-win](https://github.com/pyenv-win/pyenv-win) tool will be acquired and managed directly by [`reticulate`](https://rstudio.github.io/reticulate/). If you are using a Windows computer without Git installed, you will be prompted to allow the [pyenv-win](https://github.com/pyenv-win/pyenv-win) tool to be downloaded directly from Github to your local user application data directory (`tools::R_user_dir("CBMutils")`).

#### `spinup`
The main goal of this event is to initialize the lanscape by performing the [spinup function](https://predictiveecology.github.io/spadesCBM/#the-spinup-function). 

Cohort and stand data is prepared and passed to the [`cbmExnSpinup`](https://github.com/PredictiveEcology/CBM_core/blob/cf9c966e7bbbb29f8089411c73d030e21846ffe3/R/spinup.R#L5) function alongside growth curve data (from CBM_vol2biomass) and spinup default data (from CBM_defaults). The [`cbmExnSpinup`](https://github.com/PredictiveEcology/CBM_core/blob/cf9c966e7bbbb29f8089411c73d030e21846ffe3/R/spinup.R#L5) function sets up inputs, calls the [`cbm_exn_get_default_parameters`](https://cat-cfs.github.io/libcbm_py/cbm_exn_custom_ops.html#Appendix-1:-CBM-EXN-Default-parameters) python function that defines the model structure, and runs the carbon transfers necessary for the growth and burn cycle using [`cbm_exn_spinup`](https://cat-cfs.github.io/libcbm_py/cbm_exn_custom_ops.html#Appendix-1:-CBM-EXN-Default-parameters).

#### `postSpinup`
This short event does some basic data preparation to some of the spinup outputs to allow for use in this model. It also creates the simulation's initial [pixel groups](https://predictiveecology.github.io/spadesCBM/lexicon.html#pixel-groups). 

#### `annual`
This event is where are the carbon transfers are applied for each simulation year. Disturbances are matched to the correct records, and the transfers listed [here](https://predictiveecology.github.io/spadesCBM/index.html#order-of-operations) are applied. Details on transfer rates are found in the [following section](https://predictiveecology.github.io/spadesCBM/cbm_core.html#carbon-transfers).

#### `accumulateResults`
This final event is where outputs are saved. In the case of our example in Saskatchewan, we output and save cbmPools and Net Primary Production (NPP MAKE AND LINK TO LEXICON) for each simulation year. If paths are kept at default when running the global script, these outputs should be found here: `~/GitHub/spadesCBM/outputs`. 

### Carbon Transfers

Default parameters for simulations are available mainly from [default `.csv` files](libcbm/resources/cbm_exn) with a few pieces of information such as `mean_annual_temperature` used in decay rates calculates, `return_interval`, `min_rotations` and `max_rotations` used in the `spinup` or initialization process available in an [SQLight database](https://github.com/cat-cfs/libcbm_py/tree/main/libcbm/resources/cbm_defaults_db).  There are 18 internal carbon pools in [spadesCBM](https://github.com/PredictiveEcology/spadesCBM.git) (see Table 1 in Overview), one for the atmosphere and one for harvested wood exiting the system. Disturbances are the first carbon transfer to be applied to each record. Half the annual increment is then added (transfer from the atmosphere to the three above ground biomass pools - `Merch`, `Foliage`, and `Other`). Disturbances inputs are processes externally to [CBM_core](https://github.com/PredictiveEcology/CBM_core.git), in our example the are processes in [CBM_dataPrep_SK](https://github.com/PredictiveEcology/CBM_dataPrep_SK.git), leaving [CBM_core](https://github.com/PredictiveEcology/CBM_core.git) free of spatial data manipulations. Disturbance matrices specify the proportion of carbon in each pool to be transferred to other pools or to be taken out of the system (via forest products (pool named `Products`) or back to the atmosphere). Figure XX gives an example of transfers during a fire in SK. 

**INSERT VINI'S DIST MATRIX TRANSFER FIGURE**. 

The amount of carbon transferred from the atmosphere to the above ground biomass pools is determined from the growth curves, which were translated from $m^3/ha$ to carbon increments in [CBM_vol2biomass](https://github.com/PredictiveEcology/CBM_vol2biomass.git) and provided to [CBM_core](https://github.com/PredictiveEcology/CBM_core.git) in carbon increments (in tonnes of carbon/ha). In our example the object `simMngedSK$growth_increments` has the increments used for simulation. Dead Organic Matter ([DOM](link to lexicon)) turnover happens next and transfers carbon from the pools representing snags (`StemSnags` and `BranchSnags`), to the `MediumSoil`, and `AboveGroundFastSoil` pools. Biomass turnover follows with transfers from the `Merch`, `Foliage`, `Other`, `FineRoots` and `CoarseRoots`, to the pools representing the snags (`StemSnags` and `BranchSnags`), `AboveGroundVeryFastSoil`,	`BelowGroundFastSoil`, `AboveGroundVeryFastSoil` and `BelowGroundVeryFastSoil pools`. Carbon is never lost in the system, but increments are at times negative.  To accommodate negative increment values, a carbon transfer labelled `overmature_decline`, moves carbon between the `Merch`, `Other`, `Foliage`, `CoarseRoots` and `FineRoots` to pools representing stem an branch snags, and the `AboveGroundFastSoil`, `AboveGroundVeryFastSoil`, `BelowGroundFastSoil`, and `BelowGroundVeryFastSoil` pools. The transfers are portioned in the same way as annual process turnover and the amount is equal to the loss of each individual biomass pool according to the negative increment. Following the `overmature_decline` transfers, the second half of the growth is added to the three above ground biomass pools - `Merch`, `Foliage`, and `Other`. 

Next, the transfers due to decay are performed. Applied decay rates ($a_k$) are calculated for each DOM pool($_k$) as per **Equation 1** (see @kurz2009). 

**Equation 1.** 
$a_k = D_k * TempMod * StandMod$

Where:

$D_k$ is the base decay rate (yr−1) at a reference mean annual temperature ($RefTemp$).

$TempMod$ is a temperature modifier, as per **Equation 2**,  and $StandMod$ is a stand modifier as per **Equation 3** (@kurz1999).

**Equation 2,**

*TempMod = *$e^{((MAT_i -RefTemp)} X ln(Q_{10}) X 0.1)$

Where:

$MAT_i$ is the mean annual temperature of each spatial analysis unit.

$RefTemp$ is the reference mean annual temperature. 

$Q_{10}$ is a temperature coefficient.


**Equation 3.**

$StandMod =  1+(max_r - 1) * e^{(-b * TotBio/MaxBio)}$

Where:

$max_r$ is the open canopy decay rate multiplier (default value of 1).

$TotBio$ is the total aboveground biomass, $MaxBio$ is the maximum aboveground biomass for the specified stand type, and 

$b$ is a reduction factor calculated such that at 10% of maximum biomass, decomposition rates are reduce by 50% (set at 6.93 see @kurz1999).

The default values for base decay rate ($D_k$), $RefTemp$, $Q_10$ and $max_r$ for [spadesCBM](https://github.com/PredictiveEcology/spadesCBM.git) simulations are found [here](https://github.com/cat-cfs/libcbm_py/blob/main/libcbm/resources/cbm_exn/decay_parameters.csv). 

The final carbon transfers represents the physical transfer rate from the above- to belowground slow pool and is set at of 0.006 yr−1 ([`slowmixing`](https://github.com/cat-cfs/libcbm_py/blob/main/libcbm/resources/cbm_exn/slow_mixing_rate.csv)) is based on the transfer rate for dissolved organic C reported in the literature for some Canadian forest soils @moore2003.

The amount of carbon in the `CoarseRoots` and `FineRoots` pools depends on the carbon in the three above ground pools that absorb carbon from the atmosphere, `Merch`, `Other`, and `Foliage`. The total root biomass is estimated using empirical equations, one set of equations for hardwood (**Equation 4, 6, 7, 9**) and one for softwood species (**Equation 5, 6, 8, 10**) (@kurz2009, @li2003).

**Equation 4.**

$T_{hw}$ *=* $hw_a$ *X* $((Merch_{hw} + Foliage_{hw} + Other_{hw})$* X *$2)^{hw_b}$

**Equation 5.**

$T_{sw}$ *=* $sw_a$ *X* $((Merch_{sw} + Foliage_{sw} + Other_{sw})$* X *$2)$

**Equation 6.**

$P_{fine}$ *=* $frp_a + frp_b$ *X* $e^{((-1/frp_c)X(T_{hw} + T_{sw}))}$

**Equation 7.**

$FineRoots_{hw}$ *=* $T_{hw}$ *X* $P_{fine}$ 

**Equation 8.**

$FineRoots_{sw}$ *=* $T_{sw}$ *X* $P_{fine}$ 

**Equation 9.**

$CoarseRoots_{hw}$ *=* $T_{hw}$ *X* $(1-P_{fine})$ 

**Equation 10.**

$CoarseRoots_{sw}$ *=* $T_{sw}$ *X* $(1-P_{fine})$

On-going work to improve [CBM](link to lexicon of what we mean) is targeting all [DOM] related parameters.  @hararuk2017 used data assimilation methods which brought improvements to the turnover rates to the `FineRoots` pool, but non change to the `CoarseRoots` pool. The allocation of carbon between above ground biomass (`Merch`, `Foliage`, and `Other`) to the roots (`FineRoots`, `CoarseRoots`) implemented in [CBM](lexicon) dates from the model development (@kurz2009, @li2003). Other methods for estimating below ground biomass from above ground have been implement to estimate carbon elsewhere (example @harris2021), and a user would be justified in wanting to explore the effects of these changing these parameters (@błońska2022). In this R-based environment implementation of [CBM](lexicon), a user is free to change any of the parameters  provided to the `cbm_exn_spinup()` and `cbm_exn_step()` Python functions.


## Outputs

[CBM_core](https://github.com/PredictiveEcology/CBM_core.git) provides outputs as prescribed in the global script, the script that controls simulations. We make use of the function [SpaDES.project::setupProject](https://spades-project.predictiveecology.org/articles/i-getting-started.html#understanding-spades-projects-main-function-setupproject). While it is possible to develop a [SpaDES]() project using methods familiar to the user, the [SpaDES.project](https://spades-project.predictiveecology.org/) package streamlines this process, facilitating a clean, reproducible and reusable project setup for any project. In our example, we specify in the `globalSK.R` script that we want [`NPP`](lexicon) and [`cbmPools`](lexicon) saved every year (lines 54-56). A user could specify outputs for any pools (see Table 1 in [Overview](link to table in Overview)). A user can chose the outputs they would like to see from all objects in the [simList](lexicon). For example, a user my have interest in the quantity (in tonnes of carbon) of forest products and emissions existing the system. Our [simList](lexicon) is named `simMngedSK` (line 61 of our global script `globalSK.R`), so the object of interest would be `simMngedSK$emissionsProducts`.

Note that [CBM] does not simulate photosynthesis or autotrophic respiration. There fore, [NPP]() is calculated as the sum of net growth (i.e. growth that results in positive increment) and growth that replaces material lost to biomass turnover during the year. In young, actively growing stands, a large proportion of [NPP]() results in positive growth increment while in older, mature stands, a larger proportion of [NPP] is allocated to replacement of material lost to turnover. 


| Name              | Class      | Description                                                     |
|------------------|------------------|-------------------------------------|
| spinup_input      | List       | input parameters for the spinup functions                       |
| cbm_vars          | List       | List of 4 data tables: parameters, pools, flux, and state       |
| spinupResults     | Data frame | Pools post spinup in order of pixelGroup                        |
| pixelGroupC       | Data table | All vectors (pixelGroup columns) and pools for simulation year. |
| pixelKeep         | Data table | Tracking all pixels' pixel group through simulations            |
| cbmPools          | Data table | All pools and pixelGroups after each simulation year (or as prescribed if the simulations are very long)                 |
| NPP               | Data table | Net primary production per pixel group                          |
| emissionsProducts | matrix     | Total emissions and products for study area per simulation year |

## Links to other modules

- [CBM_defaults](https://github.com/PredictiveEcology/CBM_defaults)
- [CBM_dataPrep_SK](https://github.com/PredictiveEcology/CBM_dataPrep_SK.git)
- [CBM_vol2biomass](https://github.com/PredictiveEcology/CBM_vol2biomass)

